export enum ChannelType {
	TEXT = 'text',
	VOICE = 'voice',
}

export enum Permissions {
	ADMINISTRATOR = 'ADMINISTRATOR',
	MANAGE_SERVER = 'MANAGE_SERVER',
	MANAGE_CHANNELS = 'MANAGE_CHANNELS',
	MANAGE_MEMBERS = 'MANAGE_MEMBERS',
	CREATE_INVITES = 'CREATE_INVITES',
	MENTION_EVERYONE = 'MENTION_EVERYONE',
	SERVER_MUTED = 'SERVER_MUTED',
	MANAGE_ROLES = 'MANAGE_ROLES',
	MANAGE_ROLE_PERMISSIONS = 'MANAGE_ROLE_PERMISSIONS',
	CHANNEL_MUTED = 'CHANNEL_MUTED',
	MANAGE_WEBHOOKS = 'MANAGE_WEBHOOKS',
	MANAGE_CALL_PARTICIPANTS = 'MANAGE_CALL_PARTICIPANTS',
	MANAGE_MESSAGES = 'MANAGE_MESSAGES',
	EXTERNAL_EMOJI = 'EXTERNAL_EMOJI',
	USE_ATTACHMENTS = 'USE_ATTACHMENTS',
	ADD_REACTIONS = 'ADD_REACTIONS',
	CALL_VIDEO = 'CALL_VIDEO',
	CHANNEL_SEND = 'CHANNEL_SEND',
	CHANNEL_READ = 'CHANNEL_READ',
	SERVER_MEMBER = 'SERVER_MEMBER',
}
