name: Build Docker Image

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Docker tag, including `v`"
        required: true
        type: string

jobs:
  build-pwa-checks:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./pwa

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"
          cache-dependency-path: "./pwa/pnpm-lock.yaml"

      - name: Install dependencies
        run: pnpm install

      - name: Run lint
        run: pnpm lint

  build-backend-checks:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache: true
          cache-dependency-path: "./backend/go.sum"

      - name: Run Go vet
        run: go vet

      - name: Check Go formatting
        run: gofmt -l

      - name: Test
        run: make test

  build-docker:
    runs-on: self-hosted
    needs: [build-pwa-checks, build-backend-checks]

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract tag
        id: tag
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          	TAG="${{ github.event.inputs.tag }}"
          else
          	TAG="${GITHUB_REF#refs/tags/}"
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "Building $TAG (${{ github.event.name }})"

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/sunburn:${{ steps.tag.output.tag }}
            ${{ secrets.DOCKERHUB_USERNAME }}/sunburn:latest
            ghcr.io/${{ github.repository_owner }}/sunburn:${{ steps.tag.output.tag }}
            ghcr.io/${{ github.repository_owner }}/sunburn:latest
